name: Test & Build on PR

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      #       - name: Test
      #         run: npm run test

      - name: Build
        run: npm run build --prod --aot
